gatk_path: "/home/codespace/gatk-4.4.0.0/gatk"

R1_path: "/home/codespace/test-datasets/testdata/1_171015_HHT5NDSXX_earlycasualcaiman_XXXXXX_1.fastq.gz"
R2_path: "/home/codespace/test-datasets/testdata/1_171015_HHT5NDSXX_earlycasualcaiman_XXXXXX_2.fastq.gz"

reference_panel_path: "/home/codespace/test-datasets/reference/hg38.chrM.fa"

sample_name: "test0"

path_to_mamba_env: "/home/codespace/mambaforge/envs/trios"